name: Crear versión
on:
  push:
    tags:
      - 'v*'  # Detecta etiquetas que comienzan con "v"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar repositorio
        uses: actions/checkout@v2

      - name: Crear versión en GitHub
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Guardar la versión en archivo
        run: echo "${{ github.ref_name }}" > version.txt

      - name: Commit de version.txt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Actualizar archivo version.txt con la última versión
          file_pattern: version.txt

      - name: Guardar version.txt como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

      - name: Verificar directorio y contenido de archivos
        run: |
          echo "Archivos presentes en el directorio:"
          ls
          echo "Contenido de version.txt:"
          cat version.txt