name: Crear versión
on:
  push:
    tags:
      - 'v*'  # Detecta etiquetas que comienzan con "v"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Configurar repositorio
      - name: Configurar repositorio
        uses: actions/checkout@v3
        with:
          ref: main  # Asegúrate de usar la rama principal (o específica)

      # Crear una nueva versión en GitHub directamente
      - name: Crear versión en GitHub
        run: gh release create ${{ github.ref_name }} --notes "Release para la etiqueta ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Guardar la versión en archivo
      - name: Guardar la versión en archivo version.txt
        run: |
          echo "${{ github.ref_name }}" > version.txt
          echo "Archivo version.txt generado con contenido:"
          cat version.txt

      # Configurar rama para evitar HEAD separado
      - name: Configurar Git en una rama
        run: git checkout -b temp-branch

      # Hacer commit del archivo version.txt
      - name: Commit de version.txt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualizando archivo version.txt a la versión ${{ github.ref_name }}"
          file_pattern: version.txt

      # Hacer push del archivo version.txt
      - name: Push del archivo version.txt
        run: git push origin temp-branch